export const YOUTUBE_DATA_API_URL = 'https://www.googleapis.com/youtube/v3'
export const GOOGLE_AUTH_API_URL = 'https://www.googleapis.com/oauth2/v3/userinfo'
export const MAX_RESULTS_24 = 24
export const MAX_RESULTS_15 = 15
export const PART_SNIPPET = 'snippet'
export const PART_SNIPPET_STATS = 'snippet,statistics'
export const PART_SNIPPET_CONTENT_STATUS = 'snippet,contentDetails,status'
export const PART_SNIPPET_STATS_BRANDING = 'snippet,statistics,brandingSettings'
export const DEFAULT_ERROR_MESSAGE = 'Something bad happens'
export const COMMENTS_TURNED_OFF_MESSAGE = 'Comments are turned off.'
export const UNSUBSCRIBED = '0' // Use string '0' to indicate the channel is not subscribed.
